template = ""
rev_id = 4
template_sha = "156a8b834dacf74fc905a1ee460fe5eabb9556c6"

[replacements]
__LICENSE__ = ""
__UND2C_SRC__ = "fi"
__UND2C_TRG__ = "udm"
__UNDEFINED_SOURCE__ = "Finnish"
__UNDEFINED_TARGET__ = "Udmurt"
__UND_SRC__ = "fin"
__UND_TRG__ = "udm"
